### ISSUE TITLE
Admin account and security

### ISSUE THREAD

**Issue by webdavis** [stephenalandavis/mac-dev-playbook#4]
As the developer, I need to have the right balance of admin privileges and account security, so that I can make quick decisions and be sure this computer is secure.

### Acceptance Criteria

- [ ] The Admin account can run privileged commands without entering the admin password.
- [ ] My password DB is securely shared between this Mac and my other devices.
- [ ] This machine can be accessed via SSH.
- [ ] This machine can connect to GitHub via SSH.
- [ ] Only specific addresses can connect to this machine over the network.
- [ ] Some kind of alert system notifies the account owner if anyone tries to connect to this machine.
- [ ] Package updates should be installed automatically. See [Set up automatic updates for Brew on Mac OS X
](https://www.newpush.com/2020/05/set-up-automatic-updates-for-brew-on-mac-os-x/)
- [ ] Once finished, these operations will be contained in a separate GitHub repo (e.g. [webdavis/ansible-role-admin-account](https://github.com/webdavis/ansible-role-admin-account))

**Comment by webdavis** [comment]
## TODO

Enable Touch ID with the terminal and in Tmux by installing `pam-reattach` with brew, like so:

```bash
$ brew install pam-reattach
```

And then adding the following lines to the beginning of `/etc/pam.d/sudo`:

```bash
auth       optional       /opt/homebrew/lib/pam/pam_reattach.so
auth       sufficient     pam_tid.so
```

> **Important!**
> macOS updates override the `/etc/pam.d/sudo` file.
